M_BINANCE_API_KEY = '###'
M_BINANCE_API_SECRET = '###'

M_COINBASE_PRO_PASSPHRASE = '###'
M_COINBASE_PRO_API_SECRET = '###'
M_COINBASE_PRO_API_KEY = '###'

M_COINBASE_API_KEY = '###'
M_COINBASE_API_SECRET = '###'